name: conan-niceshade-metadata-parser CI

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Revert to default CRLF
      run: |
        git config --global core.autocrlf true
        git config --global --unset core.eol
    - name: Install dependencies
      run: pip install conan
    - name: Config
      env:
        CONAN_PASSWORD: ${{ secrets.ARTIFACTORY_APIKEY }}
      run: |
        conan remote add triada ${{ secrets.ARTIFACTORY_URL }}
        conan remote login triada ${{ secrets.ARTIFACTORY_USER }}
    - name: Build
      run: |
        conan create . -pr:h profiles/windows.profile -pr:b profiles/windows.profile -s build_type=Debug
        conan create . -pr:h profiles/windows.profile -pr:b profiles/windows.profile -s build_type=Release
        conan create . -pr:h profiles/windows.profile -pr:b profiles/windows.profile -s build_type=RelWithDebInfo
        conan create . -pr:h profiles/windows.profile -pr:b profiles/windows.profile -s build_type=MinSizeRel
    - name: Upload
      run: conan upload "niceshade-metadata-parser" -r triada -c

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
        sudo pip install conan
    - name: Config
      env:
        CONAN_PASSWORD: ${{ secrets.ARTIFACTORY_APIKEY }}
      run: |
        conan remote add triada ${{ secrets.ARTIFACTORY_URL }}
        conan remote login triada ${{ secrets.ARTIFACTORY_USER }}
    - name: Build
      run: |
        conan create . -pr:h profiles/linux.profile -pr:b profiles/linux.profile -s build_type=Debug
        conan create . -pr:h profiles/linux.profile -pr:b profiles/linux.profile -s build_type=Release
        conan create . -pr:h profiles/linux.profile -pr:b profiles/linux.profile -s build_type=RelWithDebInfo
        conan create . -pr:h profiles/linux.profile -pr:b profiles/linux.profile -s build_type=MinSizeRel
    - name: Upload
      run: conan upload "niceshade-metadata-parser" -r triada -c

  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: pip3 install conan
    - name: Config
      env:
        CONAN_PASSWORD: ${{ secrets.ARTIFACTORY_APIKEY }}
      run: |
        conan remote add triada ${{ secrets.ARTIFACTORY_URL }}
        conan remote login triada ${{ secrets.ARTIFACTORY_USER }}
    - name: Build
      run: |
        conan create . -pr:h profiles/macos.profile -pr:b profiles/macos.profile -s build_type=Debug
        conan create . -pr:h profiles/macos.profile -pr:b profiles/macos.profile -s build_type=Release
        conan create . -pr:h profiles/macos.profile -pr:b profiles/macos.profile -s build_type=RelWithDebInfo
        conan create . -pr:h profiles/macos.profile -pr:b profiles/macos.profile -s build_type=MinSizeRel
    - name: Upload
      run: conan upload "niceshade-metadata-parser" -r triada -c

  ios:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: pip3 install conan
    - name: Config
      env:
        CONAN_PASSWORD: ${{ secrets.ARTIFACTORY_APIKEY }}
      run: |
        conan remote add triada ${{ secrets.ARTIFACTORY_URL }}
        conan remote login triada ${{ secrets.ARTIFACTORY_USER }}
    - name: Build
      run: |
        conan create . -pr:h profiles/ios.profile -pr:b profiles/macos.profile -s build_type=Debug
        conan create . -pr:h profiles/ios.profile -pr:b profiles/macos.profile -s build_type=Release
        conan create . -pr:h profiles/ios.profile -pr:b profiles/macos.profile -s build_type=RelWithDebInfo
        conan create . -pr:h profiles/ios.profile -pr:b profiles/macos.profile -s build_type=MinSizeRel
    - name: Upload
      run: conan upload "niceshade-metadata-parser" -r triada -c
